const REACT_APP_SERVER_URL = process.env.REACT_APP_SERVER_URL
const REACT_APP_DEBUG = process.env.REACT_APP_DEBUG
const REACT_APP_ENCRYPTION_KEY = process.env.REACT_APP_ENCRYPTION_KEY

export { REACT_APP_SERVER_URL, REACT_APP_DEBUG, REACT_APP_ENCRYPTION_KEY }
